--db:imdb
--from:https://github.com/Nathaniel-Han/End-to-End-CardEst-Benchmark/blob/master/workloads/job-light/sub_plan_queries/job_light_single_table_sub_query.sql
--description:single-table subqueries
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=112;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005 AND t.production_year<2010;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=113;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM title t WHERE t.production_year>2010;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=112;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=113;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=117;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005;
SELECT COUNT(*) FROM movie_info mi;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2010;
SELECT COUNT(*) FROM movie_info mi;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>1990;
SELECT COUNT(*) FROM movie_info mi;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2010;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>1990;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005;
SELECT COUNT(*) FROM movie_info mi;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM title t WHERE t.production_year>2010;
SELECT COUNT(*) FROM movie_info mi;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM title t WHERE t.production_year>1990;
SELECT COUNT(*) FROM movie_info mi;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=8200;
SELECT COUNT(*) FROM title t WHERE t.production_year>2010;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2014;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=8200;
SELECT COUNT(*) FROM title t WHERE t.production_year>2014;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=8200;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM title t WHERE t.production_year>1980 AND t.production_year<1995;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM title t WHERE t.production_year>1980 AND t.production_year<1984;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM title t WHERE t.production_year>1980 AND t.production_year<2010;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=2;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=4;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=7;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=2;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005 AND t.production_year<2015;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=2;
SELECT COUNT(*) FROM title t WHERE t.production_year>2007 AND t.production_year<2010;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=1;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t WHERE t.production_year>2010;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=1;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t WHERE t.production_year>1990;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t WHERE t.production_year>1950 AND t.production_year<2000;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=398;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=398;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM title t WHERE t.production_year>1950;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005 AND t.production_year<2008;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=3;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=105;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=113;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000 AND t.production_year<2010;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=3;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM title t WHERE t.kind_Id=1;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM title t WHERE t.production_year>2010 AND t.kind_Id=1;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=8;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.kind_Id=1;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=8;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=8;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005 AND t.production_year<2010;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>1990;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=117;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=105;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=100;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM title t WHERE t.production_year>2008 AND t.production_year<2014;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=3;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=3;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=100;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005 AND t.production_year<2009;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=2;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=2;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=2;
SELECT COUNT(*) FROM title t WHERE t.production_year>1950 AND t.kind_Id=1;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000 AND t.kind_Id=1;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>1950 AND t.production_year<2000;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=398;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM movie_info mi;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000 AND t.production_year<2010;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=398;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM movie_info mi;
SELECT COUNT(*) FROM title t WHERE t.production_year>1950 AND t.production_year<2010;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=398;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM movie_info mi;
SELECT COUNT(*) FROM title t WHERE t.production_year>2008;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=8;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t WHERE t.production_year>2009;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=8;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t WHERE t.production_year>2010;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=2;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2010;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_Id=22956;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=2;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=2;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=3;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=100;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2010;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=3;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=100;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000 AND t.kind_Id=1;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005 AND t.kind_Id=1;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM title t WHERE t.production_year=1998;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=398;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_type_Id=2;
SELECT COUNT(*) FROM movie_info mi;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=8;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t WHERE t.production_year>2005;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=8;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=101;
SELECT COUNT(*) FROM movie_keyword mk;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000 AND t.production_year<2010;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=7084;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000 AND t.production_year<2005;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=16;
SELECT COUNT(*) FROM movie_companies mc;
SELECT COUNT(*) FROM cast_info ci WHERE ci.role_Id=2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_Id=7084;
SELECT COUNT(*) FROM title t WHERE t.production_year>2000;
SELECT COUNT(*) FROM movie_info mi WHERE mi.info_type_Id=3;
SELECT COUNT(*) FROM movie_info_idx mi_idx WHERE mi_Idx.info_type_Id=100;
SELECT COUNT(*) FROM cast_info ci;
SELECT COUNT(*) FROM movie_keyword mk;
